#! /bin/sh
#
# set_pac
# Copyright (C) 2022 StrayWarrior <i@straywarrior.com>

PAC_URL=${PAC_URL:-http://192.168.31.201:1079/home.pac}
SOCKS_SERVER=192.168.31.201
SOCKS_PORT=1084
NET_SERVICE=${NET_SERVICE:-Wi-Fi}


case $1 in
    on)
        networksetup -setautoproxyurl "$NET_SERVICE" "$PAC_URL"
        echo "PAC URL set to: $PAC_URL"
        ;;
    off)
        networksetup -setautoproxystate "$NET_SERVICE" off
        echo "PAC is turned off"
        ;;
    socks-on)
        networksetup -setsocksfirewallproxy "$NET_SERVICE" "$SOCKS_SERVER" "$SOCKS_PORT"
        echo "SOCKS5 proxy set to $SOCKS_SERVER:$SOCKS_PORT"
        ;;
    socks-off)
        networksetup -setsocksfirewallproxystate "$NET_SERVICE" off
        echo "SOCKS5 proxy is turned off"
        ;;
    *)
        echo "nothing to do"
        ;;
esac
